export enum GameState {
  NOT_STARTED = "NOT_STARTED",
  SELECTING = "SELECTING",
  THINKING = "THINKING",
  GUESSING = "GUESSING",
  ROUND_FINISHED = "ROUND_FINISHED",
  GAME_FINISHED = "GAME_FINISHED",
}
